// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICFCled9a78ePxCVQj1pCo0_u0eGl-xY',
    appId: '1:536655865203:web:61af80aaddf20a96d0d106',
    messagingSenderId: '536655865203',
    projectId: 'servicity-8d51b',
    authDomain: 'servicity-8d51b.firebaseapp.com',
    storageBucket: 'servicity-8d51b.appspot.com',
    measurementId: 'G-59PV1NREZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRE090MOv0LiY3ao8Q4IECKD3eW4jOwsA',
    appId: '1:536655865203:android:e8623d631693cea3d0d106',
    messagingSenderId: '536655865203',
    projectId: 'servicity-8d51b',
    storageBucket: 'servicity-8d51b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlModwqFAbUoKQc7kv7YIQnkdcD0RQy3g',
    appId: '1:536655865203:ios:c2f5df5925fcfd6fd0d106',
    messagingSenderId: '536655865203',
    projectId: 'servicity-8d51b',
    storageBucket: 'servicity-8d51b.appspot.com',
    iosClientId: '536655865203-covu1dmeg3d2e8hodlj0r2gsmb84j0o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlModwqFAbUoKQc7kv7YIQnkdcD0RQy3g',
    appId: '1:536655865203:ios:c2f5df5925fcfd6fd0d106',
    messagingSenderId: '536655865203',
    projectId: 'servicity-8d51b',
    storageBucket: 'servicity-8d51b.appspot.com',
    iosClientId: '536655865203-covu1dmeg3d2e8hodlj0r2gsmb84j0o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICFCled9a78ePxCVQj1pCo0_u0eGl-xY',
    appId: '1:536655865203:web:479b0d4ce6f4b61cd0d106',
    messagingSenderId: '536655865203',
    projectId: 'servicity-8d51b',
    authDomain: 'servicity-8d51b.firebaseapp.com',
    storageBucket: 'servicity-8d51b.appspot.com',
    measurementId: 'G-0BT7SR6E5G',
  );
}
